### ISSUE TITLE
Confligt with Contact Form 7 plugin - CORS header unset when POSTing to REST API contact form endpoint

### ISSUE THREAD

**Issue by c7nj7n** [StockManagementLabs/atum-stock-manager-for-woocommerce#15] opened 2023-01-13 21:46 UTC
A POST request to the contact form endpoint is blocked due to a missing CORS setup, which works just fine when the ATUM plugin is disabled.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://MY_DOMAIN/wp-json/contact-form-7/v1/contact-forms/MY_CONTACT_FORM_ID/feedback. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.`

Any thoughts how to have both plugins coexist?

Many thanks in advance!

**Comment by roskno** [comment] 2024-04-04 09:54
Hi @c7nj7n.

Apologies for the so late response. We haven't been checking the open issues in the repository until now.

We've been checking the issue and haven't been able to reproduce it. It seems that the problem isn't there anymore with current versions of the plugins.

I'm closing the issue, but do not hesitate to tell us if you are still getting the error.

Besat Regards,
José Andrés

**Closed** 2024-04-04 09:55 UTC
